apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      run: web-app
  replicas: 2
  template:
    metadata:
      labels:
        run: web-app
    spec:
      containers:
      - name: web-app
        image: ghcr.io/kimnjang/web-app:0.1.0
        ports:
        - containerPort: 80

